# **Data Analysis**

In [55]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

load the dataset

In [56]:
iris_dataset = load_iris()
print(iris_dataset.keys())
print(iris_dataset["feature_names"])

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


look at first 5 samples

In [57]:
print(type(iris_dataset["data"]))
print("data, rows by column / samples by features: " + str(iris_dataset["data"].shape))
# print(iris_dataset["data"][0,1]) indexing same as R dataframe
print(iris_dataset["data"][:5])

<class 'numpy.ndarray'>
data, rows by column / samples by features: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


0, 1, 2 represent different species

In [58]:
print(iris_dataset["target"].shape)
print("")
print(iris_dataset["target"])

(150,)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Seperate the date into training/testing data, X used to denote data, y for labels

In [59]:
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)
# random state is the same as seed in R random samples

print(X_train.shape) # training data(samples, features)
print(y_train.shape) # training data (labels(ie species 0,1,2))
print("")
print(X_test.shape) # test data(samples, features)
print(y_test.shape) # test data (labels(ie species 0,1,2))

(112, 4)
(112,)

(38, 4)
(38,)


## **K-nearest neighbors**

In [60]:
from sklearn.neighbors import KNeighborsClassifier
k_nearest = KNeighborsClassifier(n_neighbors=1)

In [61]:
k_nearest.fit(X_train, y_train)
print(k_nearest.get_params())

{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 1, 'p': 2, 'weights': 'uniform'}


Testing model

In [62]:
X_new = np.array([[5, 2.9, 1, 0.2]]) # has to be two dimensional([[   ]]) to use skcikit-learn
print(X_new.shape)

prediction = k_nearest.predict(X_new)
print(prediction)
print("the new flower is of species: " + iris_dataset["target_names"][prediction])


(1, 4)
[0]
['the new flower is of species: setosa']


**Evaluating the model**

In [63]:
y_prediction = k_nearest.predict(X_test)
print(y_prediction)
test_score = np.mean(y_test == y_prediction)
print(test_score)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
0.9736842105263158


In [64]:
# or alternatively

test_score = k_nearest.score(X_test, y_test)
print(test_score)

0.9736842105263158
